import assert from 'node:assert/strict';
import {validarCedula,validarPassword,validarRegistro} from '../../Frontend/validacion.js';
assert.equal(validarCedula(''),false);
assert.equal(validarCedula('00000000'),false);
assert.equal(validarCedula('1'),false);
assert.equal(validarCedula('2.000.000-6'),true);
assert.equal(validarCedula('2.000.000-7'),false);
for(const clave of ['corta','abcdefgh','ABCDEFGH','Abcdefgh','Abcdefg1','A1!'+'x'.repeat(80)]) assert.equal(validarPassword(clave),false);
assert.equal(validarPassword('Prueba!234'),true);
assert.equal(validarRegistro({nombre:'  ',email:'x@example.test',cedula:'20000006',password:'Prueba!234'})!==null,true);
assert.equal(validarRegistro({nombre:'Nombre de prueba',email:'incorrecto',cedula:'20000006',password:'Prueba!234'})!==null,true);
assert.equal(validarRegistro({nombre:'Nombre de prueba',email:'x@example.test',cedula:'20000006',password:'Prueba!234'}),null);
console.log('15 comprobaciones de validación frontend correctas.');
