server {
    listen 80;
    root /usr/share/nginx/html;
    location = / { return 302 /Frontend/principal.html; }
    location /Backend/api/usuarios/ { proxy_pass http://usuarios; }
    location /Backend/api/notificaciones/ { proxy_pass http://usuarios; }
    location /Backend/api/gestion/ { proxy_pass http://gestion; }
    location /Backend/api/recoleccion/ { proxy_pass http://recoleccion; }
    location /Backend/ { return 404; }
    location / { try_files $uri $uri/ =404; }
}
